#!/usr/bin/env node
/**
 * Generate candidates aimed at a target song and rank them.
 *
 *   node scripts/pop_review/search.mjs --target ref.mid [--blueprints 0,2,4] [--seeds 8]
 *     [--seed-base 1] [--out dir] [--top 5] [--roles f] [-- extra CLI args]
 *
 * Each candidate is generated by the native CLI at the target's tempo and
 * length, then reviewed against the target. A candidate whose hook copies a passage of the
 * target is ranked out regardless of fit. The remaining ones are ranked by
 * structure fit plus layout fit plus hook strength, and every component is
 * printed so the ranking can be argued with. The best candidates' files are
 * kept in --out.
 */

import { execFileSync } from 'node:child_process';
import { copyFileSync, mkdirSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';
import { review, reviewSong } from './review.mjs';

const repoRoot = fileURLToPath(new URL('../..', import.meta.url));
const CLI = process.env.MIDISKETCH_CLI ?? join(repoRoot, 'build', 'bin', 'midisketch_cli');

/**
 * How strong a hook is, in [0, 1]: it returns in every chorus, opens the
 * chorus, belongs to the chorus rather than the verse, and has a shape of its
 * own (a leap, some rhythm off the beat) rather than a repeated note.
 */
export function hookStrength(pop) {
  if (!pop.hookStatements) {
    return 0;
  }
  const parts = [
    Math.min(1, (pop.hookStatementsPerChorus ?? 0) / 2),
    pop.hookOpensChorusRatio ?? 0,
    pop.hookChorusExclusivity ?? 0,
    Math.min(1, (pop.hookMaxLeap ?? 0) / 5),
    Math.min(1, (pop.hookOffBeatRatio ?? 0) / 0.5),
    1 - Math.min(1, pop.hookRepeatedNoteRatio ?? 0),
  ];
  return parts.reduce((a, b) => a + b, 0) / parts.length;
}

const { values, positionals } = parseArgs({
  allowPositionals: true,
  options: {
    target: { type: 'string' },
    blueprints: { type: 'string', default: '0,1,2,3,4,5,6,7,8,9' },
    seeds: { type: 'string', default: '4' },
    'seed-base': { type: 'string', default: '1' },
    out: { type: 'string' },
    top: { type: 'string', default: '5' },
    roles: { type: 'string' },
  },
});
if (!values.target) {
  console.error(
    'usage: search.mjs --target ref.mid [--blueprints 0,2] [--seeds 4] [--out dir] [-- extra CLI args]',
  );
  process.exit(2);
}

const target = reviewSong(values.target, { roles: values.roles });
const bpm = Math.max(40, Math.min(240, Math.round(target.pop.bpm)));
const duration = Math.round(target.pop.durationSec);
const blueprints = values.blueprints.split(',').map(Number);
const seeds = Number(values.seeds);
const seedBase = Number(values['seed-base']);
const work = mkdtempSync(join(tmpdir(), 'pop-search-'));
const results = [];

for (const blueprint of blueprints) {
  for (let i = 0; i < seeds; i += 1) {
    const seed = seedBase + i;
    const dir = join(work, `bp${blueprint}_s${seed}`);
    mkdirSync(dir);
    try {
      execFileSync(
        CLI,
        [
          '--blueprint',
          String(blueprint),
          '--seed',
          String(seed),
          '--bpm',
          String(bpm),
          '--duration',
          String(duration),
          ...positionals,
        ],
        {
          cwd: dir,
          stdio: 'pipe',
        },
      );
    } catch (error) {
      console.error(`bp${blueprint} seed${seed}: generation failed: ${error.message}`);
      continue;
    }
    const result = review(join(dir, 'output.json'), {
      targetReview: target,
      target: values.target,
    });
    const hook = hookStrength(result.pop);
    const score = (result.fit.structureFit ?? 0) + (result.fit.layoutFit ?? 0) + hook;
    results.push({ blueprint, seed, dir, fit: result.fit, hook, score });
    console.error(
      `bp${blueprint} seed${seed}: score ${score.toFixed(3)}${result.fit.copyRisk ? ' (copy risk)' : ''}`,
    );
  }
}

results.sort((a, b) => Number(a.fit.copyRisk) - Number(b.fit.copyRisk) || b.score - a.score);
const top = results.slice(0, Number(values.top));
console.log(`Target: ${target.reading.song.label} at ${bpm} BPM; ${results.length} candidates`);
console.log(
  '| rank | blueprint | seed | score | structure | layout | hook | hook-to-target | copy |',
);
console.log('|---|---|---|---|---|---|---|---|---|');
top.forEach((r, i) => {
  const f = (v) => (typeof v === 'number' ? v.toFixed(3) : '—');
  console.log(
    `| ${i + 1} | ${r.blueprint} | ${r.seed} | ${f(r.score)} | ${f(r.fit.structureFit)} | ${f(r.fit.layoutFit)} | ${f(r.hook)} | ${f(r.fit.hookCopyLikeness)} | ${r.fit.copyRisk ? 'yes' : ''} |`,
  );
});
if (values.out) {
  mkdirSync(values.out, { recursive: true });
  top.forEach((r, i) => {
    for (const ext of ['json', 'mid']) {
      copyFileSync(
        join(r.dir, `output.${ext}`),
        join(values.out, `${i + 1}_bp${r.blueprint}_s${r.seed}.${ext}`),
      );
    }
  });
  console.log(`kept the top ${top.length} in ${values.out}`);
}
rmSync(work, { recursive: true, force: true });
