/**
 * @file input_mode.cpp
 * @brief Input file analysis mode implementation.
 */

#include "cli/input_mode.h"

#include <fstream>
#include <iostream>

#include "cli/display_helpers.h"
#include "midi/midi2_reader.h"
#include "midi/midi_reader.h"
#include "midisketch.h"

namespace cli {

int runInputMode(const ParsedArgs& args) {
  std::cout << "midi-sketch v" << midisketch::MidiSketch::version() << "\n\n";
  std::cout << "Analyzing: " << args.input_file << "\n\n";

  std::ifstream input_stream(args.input_file, std::ios::binary);
  if (!input_stream) {
    std::cerr << "Error: Failed to open file: " << args.input_file << "\n";
    return 1;
  }
  std::vector<uint8_t> file_data((std::istreambuf_iterator<char>(input_stream)),
                                 std::istreambuf_iterator<char>());
  input_stream.close();

  auto detected_format = midisketch::MidiReader::detectFormat(file_data.data(), file_data.size());

  if (detected_format == midisketch::DetectedMidiFormat::SMF1) {
    midisketch::MidiReader reader;
    if (!reader.read(file_data)) {
      std::cerr << "Error: " << reader.getError() << "\n";
      return 1;
    }

    const auto& midi = reader.getParsedMidi();
    std::cout << "MIDI Info:\n";
    std::cout << "  Format: SMF1 (Type " << midi.format << ")\n";
    std::cout << "  Tracks: " << midi.num_tracks << "\n";
    std::cout << "  Division: " << midi.division << " ticks/quarter\n";
    std::cout << "  BPM: " << midi.bpm << "\n";

    if (midi.hasMidiSketchMetadata()) {
      std::cout << "  Generated by: midi-sketch\n";
      std::cout << "  Metadata: " << midi.metadata << "\n";
    } else {
      std::cout << "  Generated by: (unknown - no midi-sketch metadata)\n";
    }
    std::cout << "\n";

    std::cout << "Tracks:\n";
    for (size_t i = 0; i < midi.tracks.size(); ++i) {
      const auto& track = midi.tracks[i];
      std::cout << "  [" << i << "] " << (track.name.empty() ? "(unnamed)" : track.name) << " - "
                << track.notes.size() << " notes, ch " << static_cast<int>(track.channel)
                << ", prog " << static_cast<int>(track.program) << "\n";
    }
    std::cout << "\n";

    auto report = midisketch::analyzeDissonanceFromParsedMidi(midi);
    printDissonanceSummary(report);

    auto analysis_json = midisketch::dissonanceReportToJson(report);
    std::ofstream analysis_file("analysis.json");
    if (analysis_file) {
      analysis_file << analysis_json;
      std::cout << "\nSaved: analysis.json\n";
    }

    if (args.bar_num > 0) {
      showBarNotes(midi, args.bar_num);
    }
  } else if (midisketch::MidiReader::isSMF2Format(file_data.data(), file_data.size())) {
    midisketch::Midi2Reader reader2;
    if (!reader2.read(file_data.data(), file_data.size())) {
      std::cerr << "Error: " << reader2.getError() << "\n";
      return 1;
    }

    const auto& midi2 = reader2.getParsedMidi();
    const char* format_name =
        (detected_format == midisketch::DetectedMidiFormat::SMF2_ktmidi) ? "SMF2 (ktmidi container)"
        : (detected_format == midisketch::DetectedMidiFormat::SMF2_Clip) ? "SMF2 (Clip)"
                                                                         : "SMF2 (Container)";

    std::cout << "MIDI Info:\n";
    std::cout << "  Format: " << format_name << "\n";
    std::cout << "  Tracks: " << midi2.num_tracks << "\n";
    std::cout << "  Division: " << midi2.division << " ticks/quarter\n";
    std::cout << "  BPM: " << midi2.bpm << "\n";

    if (midi2.hasMidiSketchMetadata()) {
      std::cout << "  Generated by: midi-sketch\n";
      std::cout << "  Metadata: " << midi2.metadata << "\n";
    } else {
      std::cout << "  Generated by: (unknown - no midi-sketch metadata)\n";
    }
    std::cout << "\n";

    std::cout << "Note: Dissonance analysis for SMF2 is not yet implemented.\n";
    std::cout << "Use --format smf1 when generating to enable full analysis.\n";
  } else {
    std::cerr << "Error: Unknown MIDI format\n";
    return 1;
  }

  return 0;
}

}  // namespace cli
