/**
 * @file regenerate_mode.cpp
 * @brief Regenerate mode implementation.
 */

#include "cli/regenerate_mode.h"

#include <fstream>
#include <iostream>

#include "cli/display_helpers.h"
#include "cli/generate_mode.h"
#include "midi/midi2_reader.h"
#include "midi/midi_reader.h"
#include "midisketch.h"

namespace cli {

int runRegenerateMode(const ParsedArgs& args) {
  std::cout << "midi-sketch v" << midisketch::MidiSketch::version() << "\n\n";
  std::cout << "Regenerating from: " << args.regenerate_file << "\n\n";

  std::string metadata;
  midisketch::DetectedMidiFormat original_format = midisketch::DetectedMidiFormat::Unknown;

  // Read file and detect format
  std::ifstream regen_stream(args.regenerate_file, std::ios::binary);
  if (!regen_stream) {
    std::cerr << "Error: Failed to open file: " << args.regenerate_file << "\n";
    return 1;
  }
  std::vector<uint8_t> regen_data((std::istreambuf_iterator<char>(regen_stream)),
                                  std::istreambuf_iterator<char>());
  regen_stream.close();

  original_format = midisketch::MidiReader::detectFormat(regen_data.data(), regen_data.size());

  if (midisketch::MidiReader::isSMF2Format(regen_data.data(), regen_data.size())) {
    midisketch::Midi2Reader reader2;
    if (!reader2.read(regen_data.data(), regen_data.size())) {
      std::cerr << "Error: " << reader2.getError() << "\n";
      return 1;
    }
    const auto& midi2 = reader2.getParsedMidi();
    if (!midi2.hasMidiSketchMetadata()) {
      std::cerr << "Error: No midi-sketch metadata found in file.\n";
      std::cerr << "This file was not generated by midi-sketch or metadata is missing.\n";
      return 1;
    }
    metadata = midi2.metadata;
    const char* format_name = (original_format == midisketch::DetectedMidiFormat::SMF2_ktmidi)
                                  ? "SMF2 (ktmidi container)"
                              : (original_format == midisketch::DetectedMidiFormat::SMF2_Clip)
                                  ? "SMF2 (Clip)"
                                  : "SMF2 (Container)";
    std::cout << "Format: " << format_name << "\n";
  } else if (original_format == midisketch::DetectedMidiFormat::SMF1) {
    midisketch::MidiReader reader;
    if (!reader.read(regen_data)) {
      std::cerr << "Error: " << reader.getError() << "\n";
      return 1;
    }
    const auto& midi = reader.getParsedMidi();
    if (!midi.hasMidiSketchMetadata()) {
      std::cerr << "Error: No midi-sketch metadata found in file.\n";
      std::cerr << "This file was not generated by midi-sketch or metadata is missing.\n";
      return 1;
    }
    metadata = midi.metadata;
    std::cout << "Format: Standard MIDI (SMF1)\n";
  } else {
    std::cerr << "Error: Unknown or unsupported MIDI format\n";
    return 1;
  }

  std::cout << "Original metadata: " << metadata << "\n\n";

  midisketch::SongConfig config = configFromMetadata(metadata);

  if (args.use_new_seed) {
    std::cout << "Using new seed: " << args.new_seed << " (original: " << config.seed << ")\n";
    config.seed = args.new_seed;
  }

  midisketch::MidiFormat output_format = args.midi_format;
  if (args.midi_format == midisketch::kDefaultMidiFormat &&
      original_format == midisketch::DetectedMidiFormat::SMF1) {
    output_format = midisketch::MidiFormat::SMF1;
  }

  midisketch::MidiSketch sketch;
  sketch.setMidiFormat(output_format);
  sketch.generateFromConfig(config);

  auto midi_data = sketch.getMidi();
  std::ofstream file("regenerated.mid", std::ios::binary);
  if (file) {
    file.write(reinterpret_cast<const char*>(midi_data.data()),
               static_cast<std::streamsize>(midi_data.size()));
    std::cout << "Saved: regenerated.mid (" << midi_data.size() << " bytes)\n";
  }

  const auto& song = sketch.getSong();
  std::cout << "\nRegeneration result:\n";
  std::cout << "  Total bars: " << song.arrangement().totalBars() << "\n";
  std::cout << "  Total ticks: " << song.arrangement().totalTicks() << "\n";
  std::cout << "  BPM: " << song.bpm() << "\n";
  std::cout << "  Seed: " << config.seed << "\n";

  if (args.analyze) {
    const auto& params = sketch.getParams();
    auto report = midisketch::analyzeDissonance(song, params);
    printDissonanceSummary(report);

    auto analysis_json = midisketch::dissonanceReportToJson(report);
    std::ofstream analysis_file("analysis.json");
    if (analysis_file) {
      analysis_file << analysis_json;
      std::cout << "\nSaved: analysis.json\n";
    }
  }

  return 0;
}

}  // namespace cli
