/**
 * @file regenerate_mode.cpp
 * @brief Regenerate mode implementation.
 */

#include "cli/regenerate_mode.h"

#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>

#include "cli/display_helpers.h"
#include "cli/generate_mode.h"
#include "core/json_helpers.h"
#include "midi/midi2_reader.h"
#include "midi/midi_reader.h"
#include "midisketch.h"

namespace cli {

namespace {

class ScopedStdoutSuppression {
 public:
  explicit ScopedStdoutSuppression(bool enabled) {
    if (enabled) {
      original_ = std::cout.rdbuf(suppressed_.rdbuf());
    }
  }

  ~ScopedStdoutSuppression() { restore(); }

  void restore() {
    if (original_) {
      std::cout.rdbuf(original_);
      original_ = nullptr;
    }
  }

 private:
  std::ostringstream suppressed_;
  std::streambuf* original_ = nullptr;
};

bool writeOutputFile(const char* path, const char* data, std::streamsize size) {
  std::ofstream file(path, std::ios::binary);
  if (!file) {
    std::cerr << "Error: Failed to open output file: " << path << "\n";
    return false;
  }
  file.write(data, size);
  if (!file) {
    std::cerr << "Error: Failed to write output file: " << path << "\n";
    return false;
  }
  return true;
}

std::string absoluteOutputPath(const std::string& path) {
  return std::filesystem::absolute(path).string();
}

}  // namespace

int runRegenerateMode(const ParsedArgs& args) {
  ScopedStdoutSuppression stdout_suppression(args.analyze && args.json_output);

  if (args.generation_options_specified) {
    std::cerr << "Error: Generation options cannot be combined with --regenerate. "
                 "Use --new-seed, --format, --output, --analyze, --json, --bar, or "
                 "--dump-collisions-at instead.\n";
    return 1;
  }

  std::cout << "midi-sketch v" << midisketch::MidiSketch::version() << "\n\n";
  std::cout << "Regenerating from: " << args.regenerate_file << "\n\n";

  std::string metadata;
  midisketch::DetectedMidiFormat original_format = midisketch::DetectedMidiFormat::Unknown;

  // Read file and detect format
  std::ifstream regen_stream(args.regenerate_file, std::ios::binary);
  if (!regen_stream) {
    std::cerr << "Error: Failed to open file: " << args.regenerate_file << "\n";
    return 1;
  }
  std::vector<uint8_t> regen_data((std::istreambuf_iterator<char>(regen_stream)),
                                  std::istreambuf_iterator<char>());
  regen_stream.close();

  original_format = midisketch::MidiReader::detectFormat(regen_data.data(), regen_data.size());

  if (midisketch::MidiReader::isSMF2Format(regen_data.data(), regen_data.size())) {
    midisketch::Midi2Reader reader2;
    if (!reader2.read(regen_data.data(), regen_data.size())) {
      std::cerr << "Error: " << reader2.getError() << "\n";
      return 1;
    }
    const auto& midi2 = reader2.getParsedMidi();
    if (!midi2.hasMidiSketchMetadata()) {
      std::cerr << "Error: No midi-sketch metadata found in file.\n";
      std::cerr << "This file was not generated by midi-sketch or metadata is missing.\n";
      return 1;
    }
    metadata = midi2.metadata;
    const char* format_name =
        (original_format == midisketch::DetectedMidiFormat::SMF2_ktmidi) ? "SMF2 (ktmidi container)"
        : (original_format == midisketch::DetectedMidiFormat::SMF2_Clip) ? "SMF2 (Clip)"
                                                                         : "SMF2 (Container)";
    std::cout << "Format: " << format_name << "\n";
  } else if (original_format == midisketch::DetectedMidiFormat::SMF1) {
    midisketch::MidiReader reader;
    if (!reader.read(regen_data)) {
      std::cerr << "Error: " << reader.getError() << "\n";
      return 1;
    }
    const auto& midi = reader.getParsedMidi();
    if (!midi.hasMidiSketchMetadata()) {
      std::cerr << "Error: No midi-sketch metadata found in file.\n";
      std::cerr << "This file was not generated by midi-sketch or metadata is missing.\n";
      return 1;
    }
    metadata = midi.metadata;
    std::cout << "Format: Standard MIDI (SMF1)\n";
  } else {
    std::cerr << "Error: Unknown or unsupported MIDI format\n";
    return 1;
  }

  std::cout << "Original metadata: " << metadata << "\n\n";

  const midisketch::json::Parser metadata_parser(metadata);
  if (metadata_parser.getInt("format_version", 2) < 4) {
    std::cerr << "Warning: This MIDI uses legacy metadata; regeneration restores only the fields "
                 "available in that format and may differ from the original.\n";
  }

  midisketch::SongConfig config = configFromMetadata(metadata);

  if (args.use_new_seed) {
    std::cout << "Using new seed: " << args.new_seed << " (original: " << config.seed << ")\n";
    config.seed = args.new_seed;
  }

  auto validation_error = midisketch::validateSongConfig(config);
  if (validation_error != midisketch::SongConfigError::OK) {
    std::cerr << "Error: Invalid SongConfig: " << songConfigErrorName(validation_error) << "\n";
    return 1;
  }

  midisketch::MidiFormat output_format = args.midi_format;
  if (!args.midi_format_explicit && args.midi_format == midisketch::kDefaultMidiFormat &&
      original_format == midisketch::DetectedMidiFormat::SMF1) {
    output_format = midisketch::MidiFormat::SMF1;
  }

  midisketch::MidiSketch sketch;
  sketch.setMidiFormat(output_format);
  sketch.generateFromConfig(config);
  for (const auto& warning : sketch.getWarnings()) {
    std::cerr << "Warning: " << warning << "\n";
  }

  const std::string midi_output = args.output_file.empty() ? "regenerated.mid" : args.output_file;
  const std::string analysis_output =
      args.output_file.empty() ? "analysis.json" : midi_output + ".analysis.json";

  auto midi_data = sketch.getMidi();
  if (!writeOutputFile(midi_output.c_str(), reinterpret_cast<const char*>(midi_data.data()),
                       static_cast<std::streamsize>(midi_data.size()))) {
    return 1;
  }
  std::cout << "Saved: " << absoluteOutputPath(midi_output) << " (" << midi_data.size()
            << " bytes)\n";

  const auto& song = sketch.getSong();
  std::cout << "\nRegeneration result:\n";
  std::cout << "  Total bars: " << song.arrangement().totalBars() << "\n";
  std::cout << "  Total ticks: " << song.arrangement().totalTicks() << "\n";
  std::cout << "  BPM: " << song.bpm() << "\n";
  std::cout << "  Seed: " << config.seed << "\n";

  if (args.analyze) {
    const auto& params = sketch.getParams();
    auto report = midisketch::analyzeDissonance(song, params, sketch.getHarmonyContext());

    auto analysis_json = midisketch::dissonanceReportToJson(report);
    if (args.json_output) {
      stdout_suppression.restore();
      std::cout << analysis_json;
    } else {
      printDissonanceSummary(report);

      if (!writeOutputFile(analysis_output.c_str(), analysis_json.data(),
                           static_cast<std::streamsize>(analysis_json.size()))) {
        return 1;
      }
      std::cout << "\nSaved: " << absoluteOutputPath(analysis_output) << "\n";
    }
  }

  if (args.dump_collisions_requested) {
    std::cout << "\n" << sketch.getHarmonyContext().dumpNotesAt(args.dump_collisions_tick) << "\n";
  }

  if (args.bar_num > 0) {
    if (output_format == midisketch::MidiFormat::SMF1) {
      midisketch::MidiReader reader;
      if (reader.read(midi_output)) {
        showBarNotes(reader.getParsedMidi(), args.bar_num);
      } else {
        std::cerr << "Error reading " << midi_output << " for bar inspection\n";
      }
    } else {
      std::cout << "Bar note inspection is only available for SMF1 output.\n";
    }
  }

  return 0;
}

}  // namespace cli
