/**
 * @file midi_reader.h
 * @brief MIDI file parser for reading SMF files.
 */

#pragma once

#include "core/types.h"
#include <cstdint>
#include <string>
#include <vector>

namespace midisketch {

/// @brief Parsed MIDI track info.
struct ParsedTrack {
  std::string name;               ///< Track name
  uint8_t channel = 0;            ///< MIDI channel
  uint8_t program = 0;            ///< Program number
  std::vector<NoteEvent> notes;   ///< Parsed notes
};

/// @brief Parsed MIDI file info.
struct ParsedMidi {
  uint16_t format = 0;            ///< SMF format (0, 1, or 2)
  uint16_t num_tracks = 0;        ///< Number of tracks
  uint16_t division = 480;        ///< Ticks per quarter note
  uint16_t bpm = 120;             ///< Tempo
  std::vector<ParsedTrack> tracks;  ///< Parsed tracks
  std::string metadata;           ///< MIDISKETCH metadata (JSON) if present

  /** @brief Get track by name (case-insensitive). @return Track or nullptr */
  const ParsedTrack* getTrack(const std::string& name) const;

  /** @brief Check if generated by midi-sketch. @return Has metadata */
  bool hasMidiSketchMetadata() const { return !metadata.empty(); }
};

/// @brief MIDI file reader (SMF parser).
class MidiReader {
 public:
  MidiReader() = default;

  /** @brief Read MIDI from file. @param path File path @return Success */
  bool read(const std::string& path);

  /** @brief Read MIDI from memory. @param data Binary data @return Success */
  bool read(const std::vector<uint8_t>& data);

  /** @brief Get parsed MIDI data. @return ParsedMidi reference */
  const ParsedMidi& getParsedMidi() const { return midi_; }

  /** @brief Get last error message. @return Error string */
  const std::string& getError() const { return error_; }

 private:
  ParsedMidi midi_;
  std::string error_;

  uint32_t readVariableLength(const uint8_t* data, size_t& offset, size_t max_size);
  bool parseHeader(const uint8_t* data, size_t size);
  bool parseTrack(const uint8_t* data, size_t size);
};

}  // namespace midisketch
